ProFive/AppFive/urls.py
from django.urls import path
from AppFive import views

app_name = 'AppFive'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login')
]

ProFive/ProFive/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from AppFive import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('AppFive/', include('AppFive.urls')),
    path('logout', views.user_logout,name='user_logout'),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProFive/AppFive/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic =models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

ProFive/AppFive/forms.py
from django import forms
from django.contrib.auth.models import User
from AppFive.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

ProFive/AppFive/views.py
from django.shortcuts import render
from AppFive.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

def index(request):
    return render(request, 'AppFive/index.html')

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'AppFive/registration.html',
                    {'user_form':user_form,
                    'profile_form':profile_form,
                    'registered':registered})

def user_login(request):
     if request.method == 'POST':
         username = request.POST.get('username')
         password = request.POST.get('password')

         user = authenticate(username=username,password=password)

         if user:
             if user.is_active:
                 login(request,user)
                 return HttpResponseRedirect(reverse('index'))
             else:
                return HttpResponse("Your account is not active!")
         else:
            print("{}} tried to login and failed".format(username))
            return HttpResponse("Invalid login credentials")
     else:
        return render(request, 'AppFive/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

ProFive/templates/AppFive/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href={% url 'index' %}>DJANGO</a></li>
            <li><a class="navbar-link" href={% url 'admin:index' %}>Admin</a></li>
            <li><a class="navbar-link" href={% url 'AppFive:register' %}>Register</a></li>

            {% if user.is_authenticated %}
              <li><a class='navbar-link' href="{% url 'user_logout' %}">Logout</a></li>
            {% else %}
              <li><a class='navbar-link' href="{% url 'AppFive:user_login' %}">Login</a></li>
            {% endif %}

        </ul>
      </div>
    </nav>

    <div class="">
        {% block body_block %}
        {% endblock %}
    </div>

  </body>
</html>

ProFive/templates/AppFive/index.html
{% extends "AppFive/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock %}

ProFive/templates/AppFive/login.html
{% extends 'AppFive/base.html'%}

{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'AppFive:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username"</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

ProFive/templates/AppFive/registration.html
{% extends 'AppFive/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
    {% endif %}
    
</div>
{% endblock %}